package app.curious.lineflow

import androidx.compose.ui.geometry.Offset

data class Node(
    val id: Int,
    // Position in a normalized coordinate space (0.0 to 1.0)
    val position: Offset,
)

data class Edge(
    val node1Id: Int,
    val node2Id: Int,
    var isVisited: Boolean = false,
) {
    fun containsNode(nodeId: Int): Boolean = nodeId == node1Id || nodeId == node2Id
}

data class HintStep(
    val text: String,
    val showValidStarts: Boolean = false,
    val showFirstEdge: Boolean = false,
)

data class LevelHints(
    val validStartNodeIds: List<Int>,
    val firstEdge: Pair<Int, Int>?,
    val steps: List<HintStep>,
)

data class Level(
    val id: Int,
    val name: String,
    val nodes: List<Node>,
    val edges: List<Edge>,
    val hints: LevelHints,
)

/**
 * All levels are generated by `.scripts/leveldesign/build.py --write`.
 * Edit the catalog there, not this file: every level is verified to be
 * drawable in one stroke and laid out with enough room for a finger.
 */
object LevelManager {
    val levels = listOf(
        // Level 1: The Triangle - 3 dots, 3 lines, circuit
        // One solution: 0-1-2-0
        Level(
            id = 1,
            name = "The Triangle",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(1.000f, 0.866f)),
                Node(2, Offset(0.000f, 0.866f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "A loop can be drawn from any corner."),
                    HintStep(text = "Every dot works as a start. Try the top one. From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 2: The Square - 4 dots, 4 lines, circuit
        // One solution: 0-1-2-3-0
        Level(
            id = 2,
            name = "The Square",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(1.000f, 0.000f)),
                Node(2, Offset(1.000f, 1.000f)),
                Node(3, Offset(0.000f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Another loop. Pick a corner and go around."),
                    HintStep(text = "Every dot works as a start. Try the top-left one. From the top-left dot, head right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 3: The Star - 5 dots, 5 lines, circuit
        // One solution: 0-2-4-1-3-0
        Level(
            id = 3,
            name = "The Star",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(1.000f, 0.363f)),
                Node(2, Offset(0.809f, 0.951f)),
                Node(3, Offset(0.191f, 0.951f)),
                Node(4, Offset(0.000f, 0.363f)),
            ),
            edges = listOf(
                Edge(0, 2), Edge(2, 4), Edge(4, 1), Edge(1, 3), Edge(3, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4),
                firstEdge = Pair(0, 2),
                steps = listOf(
                    HintStep(text = "Lines may cross. Draw the star the way you did as a kid."),
                    HintStep(text = "Every dot works as a start. Try the top one. From the top dot, head down first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 4: The House - 5 dots, 6 lines, path 0->1
        // One solution: 0-4-1-0-3-2-1
        Level(
            id = 4,
            name = "The House",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.333f)),
                Node(1, Offset(0.667f, 0.333f)),
                Node(2, Offset(0.667f, 1.000f)),
                Node(3, Offset(0.000f, 1.000f)),
                Node(4, Offset(0.333f, 0.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 0), Edge(0, 4), Edge(4, 1),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1),
                firstEdge = Pair(0, 4),
                steps = listOf(
                    HintStep(text = "Count the lines at each dot. Two dots have three: start at one of them."),
                    HintStep(text = "Start at the top-left dot; you will finish at the top-right one. From the top-left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 5: The Bow Tie - 5 dots, 6 lines, circuit
        // One solution: 0-1-2-3-4-2-0
        Level(
            id = 5,
            name = "The Bow Tie",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.000f, 0.714f)),
                Node(2, Offset(0.500f, 0.357f)),
                Node(3, Offset(1.000f, 0.000f)),
                Node(4, Offset(1.000f, 0.714f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(2, 3), Edge(2, 4), Edge(3, 4),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "The middle dot is visited twice. Finish one wing before the other."),
                    HintStep(text = "Every dot works as a start. Try the top-left one. From the top-left dot, head down first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 6: The Window - 6 dots, 7 lines, path 1->4
        // One solution: 1-0-3-4-5-2-1-4
        Level(
            id = 6,
            name = "The Window",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.500f, 0.000f)),
                Node(2, Offset(1.000f, 0.000f)),
                Node(3, Offset(0.000f, 0.500f)),
                Node(4, Offset(0.500f, 0.500f)),
                Node(5, Offset(1.000f, 0.500f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(3, 4), Edge(4, 5), Edge(0, 3), Edge(1, 4),
                Edge(2, 5),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(1, 4),
                firstEdge = Pair(1, 0),
                steps = listOf(
                    HintStep(text = "The corners are easy; the two middle dots decide where you start."),
                    HintStep(text = "Start at the top dot; you will finish at the bottom one. From the top dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 7: The Fan - 5 dots, 7 lines, path 2->4
        // One solution: 2-0-1-2-4-1-3-4
        Level(
            id = 7,
            name = "The Fan",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.000f, 0.333f)),
                Node(2, Offset(1.000f, 0.333f)),
                Node(3, Offset(0.100f, 0.933f)),
                Node(4, Offset(0.900f, 0.933f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(3, 4),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 4),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "One dot on the right and one at the bottom have odd lines."),
                    HintStep(text = "Start at the right dot; you will finish at the bottom-right one. From the right dot, head up-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 8: The Envelope - 5 dots, 8 lines, path 2->3
        // One solution: 3-2-1-0-3-1-4-0-2
        Level(
            id = 8,
            name = "The Envelope",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.333f)),
                Node(1, Offset(0.667f, 0.333f)),
                Node(2, Offset(0.667f, 1.000f)),
                Node(3, Offset(0.000f, 1.000f)),
                Node(4, Offset(0.333f, 0.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 0), Edge(0, 4), Edge(4, 1),
                Edge(0, 2), Edge(1, 3),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 3),
                firstEdge = Pair(3, 2),
                steps = listOf(
                    HintStep(text = "The famous one. Start at a bottom corner and end at the other."),
                    HintStep(text = "Start at the bottom-left dot; you will finish at the bottom-right one. From the bottom-left dot, head right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 9: The Hexagon - 6 dots, 9 lines, circuit
        // One solution: 0-1-2-3-4-5-0-2-4-0
        Level(
            id = 9,
            name = "The Hexagon",
            nodes = listOf(
                Node(0, Offset(0.433f, 0.000f)),
                Node(1, Offset(0.866f, 0.250f)),
                Node(2, Offset(0.866f, 0.750f)),
                Node(3, Offset(0.433f, 1.000f)),
                Node(4, Offset(0.000f, 0.750f)),
                Node(5, Offset(0.000f, 0.250f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 0),
                Edge(0, 2), Edge(2, 4), Edge(4, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "A loop with a triangle inside. All even, but the triangle can strand a corner."),
                    HintStep(text = "Every dot works as a start. Try the top one. From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 10: The Pentacle - 5 dots, 10 lines, circuit
        // One solution: 0-1-2-3-4-0-2-4-1-3-0
        Level(
            id = 10,
            name = "The Pentacle",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(1.000f, 0.363f)),
                Node(2, Offset(0.809f, 0.951f)),
                Node(3, Offset(0.191f, 0.951f)),
                Node(4, Offset(0.000f, 0.363f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "A star inside a ring. Every point has four lines, so start anywhere."),
                    HintStep(text = "Every dot works as a start. Try the top one. From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 11: The Shield - 7 dots, 11 lines, path 1->2
        // One solution: 1-0-2-4-5-1-3-6-4-3-5-2
        Level(
            id = 11,
            name = "The Shield",
            nodes = listOf(
                Node(0, Offset(0.417f, 0.000f)),
                Node(1, Offset(0.000f, 0.278f)),
                Node(2, Offset(0.833f, 0.278f)),
                Node(3, Offset(0.000f, 0.722f)),
                Node(4, Offset(0.833f, 0.722f)),
                Node(5, Offset(0.417f, 0.417f)),
                Node(6, Offset(0.417f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 3), Edge(2, 4), Edge(1, 5), Edge(2, 5),
                Edge(5, 3), Edge(5, 4), Edge(3, 6), Edge(4, 6), Edge(3, 4),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(1, 2),
                firstEdge = Pair(1, 0),
                steps = listOf(
                    HintStep(text = "The two shoulders are the odd dots. Everything below them is loops."),
                    HintStep(text = "Start at the top-left dot; you will finish at the top-right one.", showValidStarts = true),
                    HintStep(text = "From the top-left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 12: The Sailboat - 8 dots, 11 lines, path 1->2
        // One solution: 1-0-4-3-2-1-4-6-5-7-4-2
        Level(
            id = 12,
            name = "The Sailboat",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.500f)),
                Node(1, Offset(0.250f, 0.800f)),
                Node(2, Offset(0.750f, 0.800f)),
                Node(3, Offset(1.000f, 0.500f)),
                Node(4, Offset(0.500f, 0.500f)),
                Node(5, Offset(0.500f, 0.000f)),
                Node(6, Offset(0.850f, 0.150f)),
                Node(7, Offset(0.150f, 0.150f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(0, 4), Edge(4, 3), Edge(1, 4),
                Edge(2, 4), Edge(5, 6), Edge(6, 4), Edge(5, 7), Edge(7, 4),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(1, 2),
                firstEdge = Pair(1, 0),
                steps = listOf(
                    HintStep(text = "The two hull dots have three lines each. Sail from one to the other."),
                    HintStep(text = "Start at the bottom-left dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the bottom-left dot, head up-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 13: The Hexagram - 6 dots, 12 lines, circuit
        // One solution: 0-1-2-3-4-5-3-1-5-0-2-4-0
        Level(
            id = 13,
            name = "The Hexagram",
            nodes = listOf(
                Node(0, Offset(0.433f, 0.000f)),
                Node(1, Offset(0.866f, 0.250f)),
                Node(2, Offset(0.866f, 0.750f)),
                Node(3, Offset(0.433f, 1.000f)),
                Node(4, Offset(0.000f, 0.750f)),
                Node(5, Offset(0.000f, 0.250f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 0),
                Edge(0, 2), Edge(1, 3), Edge(2, 4), Edge(3, 5), Edge(4, 0), Edge(5, 1),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Two triangles and a ring. Cross the middle freely; only dots count."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 14: The Gem - 8 dots, 13 lines, path 2->5
        // One solution: 2-0-1-2-4-6-2-5-3-1-5-6-7-5
        Level(
            id = 14,
            name = "The Gem",
            nodes = listOf(
                Node(0, Offset(0.425f, 0.000f)),
                Node(1, Offset(0.200f, 0.225f)),
                Node(2, Offset(0.650f, 0.225f)),
                Node(3, Offset(0.000f, 0.500f)),
                Node(4, Offset(0.850f, 0.500f)),
                Node(5, Offset(0.200f, 0.775f)),
                Node(6, Offset(0.650f, 0.775f)),
                Node(7, Offset(0.425f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(3, 5), Edge(1, 5),
                Edge(2, 4), Edge(4, 6), Edge(2, 6), Edge(5, 6), Edge(5, 7), Edge(6, 7),
                Edge(2, 5),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 5),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "One long facet cuts across the gem. Its two ends are your start and finish."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 15: The Ladder - 8 dots, 13 lines, path 1->6
        // One solution: 1-0-2-1-3-2-4-3-5-4-6-5-7-6
        Level(
            id = 15,
            name = "The Ladder",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.476f, 0.000f)),
                Node(2, Offset(0.000f, 0.333f)),
                Node(3, Offset(0.476f, 0.333f)),
                Node(4, Offset(0.000f, 0.667f)),
                Node(5, Offset(0.476f, 0.667f)),
                Node(6, Offset(0.000f, 1.000f)),
                Node(7, Offset(0.476f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(2, 1), Edge(1, 3), Edge(2, 3), Edge(2, 4),
                Edge(4, 3), Edge(3, 5), Edge(4, 5), Edge(4, 6), Edge(6, 5), Edge(5, 7),
                Edge(6, 7),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(1, 6),
                firstEdge = Pair(1, 0),
                steps = listOf(
                    HintStep(text = "Rails, rungs and braces. The odd dots are where the braces stop."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 16: The Necklace - 10 dots, 13 lines, path 4->5
        // One solution: 4-3-1-0-2-3-5-6-7-9-8-6-4-5
        Level(
            id = 16,
            name = "The Necklace",
            nodes = listOf(
                Node(0, Offset(0.167f, 0.000f)),
                Node(1, Offset(0.000f, 0.167f)),
                Node(2, Offset(0.333f, 0.167f)),
                Node(3, Offset(0.167f, 0.333f)),
                Node(4, Offset(0.000f, 0.500f)),
                Node(5, Offset(0.333f, 0.500f)),
                Node(6, Offset(0.167f, 0.667f)),
                Node(7, Offset(0.000f, 0.833f)),
                Node(8, Offset(0.333f, 0.833f)),
                Node(9, Offset(0.167f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 3), Edge(3, 2), Edge(2, 0), Edge(3, 4), Edge(4, 6),
                Edge(6, 5), Edge(5, 3), Edge(6, 7), Edge(7, 9), Edge(9, 8), Edge(8, 6),
                Edge(4, 5),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(4, 5),
                firstEdge = Pair(4, 3),
                steps = listOf(
                    HintStep(text = "Each shared dot is a door. Close a diamond before you walk through it."),
                    HintStep(text = "Start at the left dot; you will finish at the right one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 17: The Twin Envelopes - 8 dots, 14 lines, path 3->5
        // One solution: 3-0-1-2-5-4-3-1-6-0-4-2-7-1-5
        Level(
            id = 17,
            name = "The Twin Envelopes",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.250f)),
                Node(1, Offset(0.500f, 0.250f)),
                Node(2, Offset(1.000f, 0.250f)),
                Node(3, Offset(0.000f, 0.750f)),
                Node(4, Offset(0.500f, 0.750f)),
                Node(5, Offset(1.000f, 0.750f)),
                Node(6, Offset(0.250f, 0.000f)),
                Node(7, Offset(0.750f, 0.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(3, 4), Edge(4, 5), Edge(0, 3), Edge(2, 5),
                Edge(0, 4), Edge(1, 3), Edge(1, 5), Edge(2, 4), Edge(0, 6), Edge(6, 1),
                Edge(1, 7), Edge(7, 2),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(3, 5),
                firstEdge = Pair(3, 0),
                steps = listOf(
                    HintStep(text = "Two envelopes share a middle. The bottom corners are still the odd ones."),
                    HintStep(text = "Start at the bottom-left dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the bottom-left dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 18: The Octagram - 8 dots, 16 lines, circuit
        // One solution: 0-1-2-3-4-5-6-7-0-3-6-1-4-7-2-5-0
        Level(
            id = 18,
            name = "The Octagram",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.854f, 0.146f)),
                Node(2, Offset(1.000f, 0.500f)),
                Node(3, Offset(0.854f, 0.854f)),
                Node(4, Offset(0.500f, 1.000f)),
                Node(5, Offset(0.146f, 0.854f)),
                Node(6, Offset(0.000f, 0.500f)),
                Node(7, Offset(0.146f, 0.146f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 6),
                Edge(6, 7), Edge(7, 0), Edge(0, 3), Edge(1, 4), Edge(2, 5), Edge(3, 6),
                Edge(4, 7), Edge(5, 0), Edge(6, 1), Edge(7, 2),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Eight points and a star of long chords. All even: any start works."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 19: The Lattice - 9 dots, 16 lines, path 2->6
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6
        Level(
            id = 19,
            name = "The Lattice",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.500f, 0.000f)),
                Node(2, Offset(1.000f, 0.000f)),
                Node(3, Offset(0.000f, 0.500f)),
                Node(4, Offset(0.500f, 0.500f)),
                Node(5, Offset(1.000f, 0.500f)),
                Node(6, Offset(0.000f, 1.000f)),
                Node(7, Offset(0.500f, 1.000f)),
                Node(8, Offset(1.000f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(7, 8),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 6),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "A braced grid. The odd dots sit at two opposite corners."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 20: The Clover - 13 dots, 18 lines, circuit
        // One solution: 0-1-2-3-0-4-5-6-0-7-8-11-5-10-2-12-8-9-0
        Level(
            id = 20,
            name = "The Clover",
            nodes = listOf(
                Node(0, Offset(0.456f, 0.474f)),
                Node(1, Offset(0.312f, 0.253f)),
                Node(2, Offset(0.456f, 0.000f)),
                Node(3, Offset(0.599f, 0.253f)),
                Node(4, Offset(0.719f, 0.460f)),
                Node(5, Offset(0.866f, 0.711f)),
                Node(6, Offset(0.575f, 0.708f)),
                Node(7, Offset(0.336f, 0.708f)),
                Node(8, Offset(0.046f, 0.711f)),
                Node(9, Offset(0.193f, 0.460f)),
                Node(10, Offset(0.912f, 0.211f)),
                Node(11, Offset(0.456f, 1.000f)),
                Node(12, Offset(0.000f, 0.211f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 0), Edge(0, 4), Edge(4, 5),
                Edge(5, 6), Edge(6, 0), Edge(0, 7), Edge(7, 8), Edge(8, 9), Edge(9, 0),
                Edge(2, 10), Edge(10, 5), Edge(5, 11), Edge(11, 8), Edge(8, 12), Edge(12, 2),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Three leaves on one hub, all even. Do not leave a leaf half done."),
                    HintStep(text = "Every dot works as a start. Try the center one.", showValidStarts = true),
                    HintStep(text = "From the center dot, head up-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 21: The Pyramid - 10 dots, 18 lines, circuit
        // One solution: 0-1-2-4-1-3-4-5-8-4-7-3-6-7-8-9-5-2-0
        Level(
            id = 21,
            name = "The Pyramid",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.333f, 0.290f)),
                Node(2, Offset(0.667f, 0.290f)),
                Node(3, Offset(0.167f, 0.580f)),
                Node(4, Offset(0.500f, 0.580f)),
                Node(5, Offset(0.833f, 0.580f)),
                Node(6, Offset(0.000f, 0.870f)),
                Node(7, Offset(0.333f, 0.870f)),
                Node(8, Offset(0.667f, 0.870f)),
                Node(9, Offset(1.000f, 0.870f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(3, 7), Edge(4, 5), Edge(4, 7),
                Edge(4, 8), Edge(5, 8), Edge(5, 9), Edge(6, 7), Edge(7, 8), Edge(8, 9),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Ten dots, all even. The middle rows carry six lines each; do not strand them."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 22: The Hourglass - 11 dots, 18 lines, circuit
        // One solution: 0-1-2-3-6-7-8-9-10-8-6-10-3-4-5-0-2-4-0
        Level(
            id = 22,
            name = "The Hourglass",
            nodes = listOf(
                Node(0, Offset(0.216f, 0.000f)),
                Node(1, Offset(0.433f, 0.125f)),
                Node(2, Offset(0.433f, 0.375f)),
                Node(3, Offset(0.216f, 0.500f)),
                Node(4, Offset(0.000f, 0.375f)),
                Node(5, Offset(0.000f, 0.125f)),
                Node(6, Offset(0.433f, 0.625f)),
                Node(7, Offset(0.433f, 0.875f)),
                Node(8, Offset(0.216f, 1.000f)),
                Node(9, Offset(0.000f, 0.875f)),
                Node(10, Offset(0.000f, 0.625f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 0),
                Edge(0, 2), Edge(2, 4), Edge(4, 0), Edge(3, 6), Edge(6, 7), Edge(7, 8),
                Edge(8, 9), Edge(9, 10), Edge(10, 3), Edge(6, 8), Edge(8, 10), Edge(10, 6),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Two hexagons share one dot. Whatever you leave behind on one side is lost."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 23: The Hourglass Star - 8 dots, 19 lines, path 2->3
        // One solution: 2-0-1-2-3-4-0-3-1-4-2-7-5-6-3-5-2-6-7-3
        Level(
            id = 23,
            name = "The Hourglass Star",
            nodes = listOf(
                Node(0, Offset(0.263f, 0.000f)),
                Node(1, Offset(0.526f, 0.191f)),
                Node(2, Offset(0.425f, 0.500f)),
                Node(3, Offset(0.100f, 0.500f)),
                Node(4, Offset(0.000f, 0.191f)),
                Node(5, Offset(0.263f, 1.000f)),
                Node(6, Offset(0.000f, 0.809f)),
                Node(7, Offset(0.526f, 0.809f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(5, 6), Edge(6, 3),
                Edge(2, 7), Edge(7, 5), Edge(5, 3), Edge(6, 2), Edge(3, 7), Edge(2, 5),
                Edge(7, 6),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 3),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "Two stars share an edge. The dots on that edge carry seven lines: start on one."),
                    HintStep(text = "Start at the right dot; you will finish at the left one.", showValidStarts = true),
                    HintStep(text = "From the right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 24: The Wheel - 10 dots, 20 lines, circuit
        // One solution: 0-1-2-3-4-0-5-6-7-8-9-5-1-6-2-7-3-8-4-9-0
        Level(
            id = 24,
            name = "The Wheel",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(1.000f, 0.363f)),
                Node(2, Offset(0.809f, 0.951f)),
                Node(3, Offset(0.191f, 0.951f)),
                Node(4, Offset(0.000f, 0.363f)),
                Node(5, Offset(0.624f, 0.356f)),
                Node(6, Offset(0.700f, 0.591f)),
                Node(7, Offset(0.500f, 0.736f)),
                Node(8, Offset(0.300f, 0.591f)),
                Node(9, Offset(0.376f, 0.356f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(5, 6),
                Edge(6, 7), Edge(7, 8), Edge(8, 9), Edge(9, 5), Edge(0, 5), Edge(0, 9),
                Edge(1, 6), Edge(1, 5), Edge(2, 7), Edge(2, 6), Edge(3, 8), Edge(3, 7),
                Edge(4, 9), Edge(4, 8),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Two rings and a zigzag. Work in wedges so no spoke is stranded."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 25: The Star Fort - 10 dots, 20 lines, circuit
        // One solution: 0-1-2-3-4-0-2-4-1-3-0-5-1-6-2-7-3-8-4-9-0
        Level(
            id = 25,
            name = "The Star Fort",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.097f)),
                Node(1, Offset(0.813f, 0.324f)),
                Node(2, Offset(0.693f, 0.691f)),
                Node(3, Offset(0.307f, 0.691f)),
                Node(4, Offset(0.187f, 0.324f)),
                Node(5, Offset(0.809f, 0.000f)),
                Node(6, Offset(1.000f, 0.588f)),
                Node(7, Offset(0.500f, 0.951f)),
                Node(8, Offset(0.000f, 0.588f)),
                Node(9, Offset(0.191f, 0.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(0, 5), Edge(5, 1),
                Edge(1, 6), Edge(6, 2), Edge(2, 7), Edge(7, 3), Edge(3, 8), Edge(8, 4),
                Edge(4, 9), Edge(9, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "A pentacle with five bastions. Each bastion is a detour you must take once."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 26: The Butterfly - 9 dots, 20 lines, circuit
        // One solution: 0-1-2-3-4-0-2-4-1-3-0-5-6-7-8-0-6-8-5-7-0
        Level(
            id = 26,
            name = "The Butterfly",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.263f)),
                Node(1, Offset(0.309f, 0.526f)),
                Node(2, Offset(0.000f, 0.425f)),
                Node(3, Offset(0.000f, 0.100f)),
                Node(4, Offset(0.309f, 0.000f)),
                Node(5, Offset(0.691f, 0.000f)),
                Node(6, Offset(1.000f, 0.100f)),
                Node(7, Offset(1.000f, 0.425f)),
                Node(8, Offset(0.691f, 0.526f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(0, 5), Edge(5, 6),
                Edge(6, 7), Edge(7, 8), Edge(8, 0), Edge(0, 6), Edge(5, 7), Edge(6, 8),
                Edge(7, 0), Edge(8, 5),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Two stars pinched at one dot. That dot is the only way between the wings."),
                    HintStep(text = "Every dot works as a start. Try the center one.", showValidStarts = true),
                    HintStep(text = "From the center dot, head down-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 27: The Hex Fort - 12 dots, 21 lines, circuit
        // One solution: 0-1-2-3-4-5-0-2-4-0-6-1-7-2-8-3-9-4-10-5-11-0
        Level(
            id = 27,
            name = "The Hex Fort",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.100f)),
                Node(1, Offset(0.789f, 0.266f)),
                Node(2, Offset(0.789f, 0.600f)),
                Node(3, Offset(0.500f, 0.766f)),
                Node(4, Offset(0.211f, 0.600f)),
                Node(5, Offset(0.211f, 0.266f)),
                Node(6, Offset(0.750f, 0.000f)),
                Node(7, Offset(1.000f, 0.433f)),
                Node(8, Offset(0.750f, 0.866f)),
                Node(9, Offset(0.250f, 0.866f)),
                Node(10, Offset(0.000f, 0.433f)),
                Node(11, Offset(0.250f, 0.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 0),
                Edge(0, 2), Edge(2, 4), Edge(4, 0), Edge(0, 6), Edge(6, 1), Edge(1, 7),
                Edge(7, 2), Edge(2, 8), Edge(8, 3), Edge(3, 9), Edge(9, 4), Edge(4, 10),
                Edge(10, 5), Edge(5, 11), Edge(11, 0),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Six bastions and a triangle inside. All even, but the triangle strands corners."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 28: The Dumbbell - 10 dots, 21 lines, path 2->8
        // One solution: 2-0-1-2-3-4-0-3-1-4-2-8-7-6-5-9-8-6-9-7-5-8
        Level(
            id = 28,
            name = "The Dumbbell",
            nodes = listOf(
                Node(0, Offset(0.165f, 0.000f)),
                Node(1, Offset(0.329f, 0.120f)),
                Node(2, Offset(0.266f, 0.313f)),
                Node(3, Offset(0.063f, 0.313f)),
                Node(4, Offset(0.000f, 0.120f)),
                Node(5, Offset(0.165f, 1.000f)),
                Node(6, Offset(0.000f, 0.880f)),
                Node(7, Offset(0.063f, 0.687f)),
                Node(8, Offset(0.266f, 0.687f)),
                Node(9, Offset(0.329f, 0.880f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(5, 6), Edge(6, 7),
                Edge(7, 8), Edge(8, 9), Edge(9, 5), Edge(5, 7), Edge(6, 8), Edge(7, 9),
                Edge(8, 5), Edge(9, 6), Edge(2, 8),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 8),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "Two stars, one bar. Cross the bar exactly once, with nothing left behind."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 29: The Serpent - 12 dots, 23 lines, path 2->9
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-9-7-10-8-11-10-9
        Level(
            id = 29,
            name = "The Serpent",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.290f, 0.000f)),
                Node(2, Offset(0.580f, 0.000f)),
                Node(3, Offset(0.000f, 0.333f)),
                Node(4, Offset(0.290f, 0.333f)),
                Node(5, Offset(0.580f, 0.333f)),
                Node(6, Offset(0.000f, 0.667f)),
                Node(7, Offset(0.290f, 0.667f)),
                Node(8, Offset(0.580f, 0.667f)),
                Node(9, Offset(0.000f, 1.000f)),
                Node(10, Offset(0.290f, 1.000f)),
                Node(11, Offset(0.580f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(6, 9), Edge(9, 7), Edge(7, 8),
                Edge(7, 10), Edge(10, 8), Edge(8, 11), Edge(9, 10), Edge(10, 11),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 9),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "Braces everywhere. Top-right and bottom-left are the odd dots."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 30: The Rocket - 12 dots, 23 lines, path 3->9
        // One solution: 3-1-0-2-1-4-2-5-4-3-6-4-7-5-8-7-6-9-7-10-8-11-10-9
        Level(
            id = 30,
            name = "The Rocket",
            nodes = listOf(
                Node(0, Offset(0.267f, 0.000f)),
                Node(1, Offset(0.134f, 0.233f)),
                Node(2, Offset(0.401f, 0.233f)),
                Node(3, Offset(0.000f, 0.465f)),
                Node(4, Offset(0.267f, 0.465f)),
                Node(5, Offset(0.535f, 0.465f)),
                Node(6, Offset(0.000f, 0.733f)),
                Node(7, Offset(0.267f, 0.733f)),
                Node(8, Offset(0.535f, 0.733f)),
                Node(9, Offset(0.000f, 1.000f)),
                Node(10, Offset(0.267f, 1.000f)),
                Node(11, Offset(0.535f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(4, 5), Edge(3, 6), Edge(6, 4), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(6, 9), Edge(9, 7), Edge(7, 8),
                Edge(7, 10), Edge(10, 8), Edge(8, 11), Edge(9, 10), Edge(10, 11),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(3, 9),
                firstEdge = Pair(3, 1),
                steps = listOf(
                    HintStep(text = "A nose cone on a braced body. One odd dot is where the cone meets the body."),
                    HintStep(text = "Start at the left dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 31: The Snowflake - 12 dots, 24 lines, circuit
        // One solution: 0-1-2-3-4-5-0-6-7-8-9-10-11-6-1-7-2-8-3-9-4-10-5-11-0
        Level(
            id = 31,
            name = "The Snowflake",
            nodes = listOf(
                Node(0, Offset(0.433f, 0.000f)),
                Node(1, Offset(0.866f, 0.250f)),
                Node(2, Offset(0.866f, 0.750f)),
                Node(3, Offset(0.433f, 1.000f)),
                Node(4, Offset(0.000f, 0.750f)),
                Node(5, Offset(0.000f, 0.250f)),
                Node(6, Offset(0.553f, 0.292f)),
                Node(7, Offset(0.673f, 0.500f)),
                Node(8, Offset(0.553f, 0.708f)),
                Node(9, Offset(0.313f, 0.708f)),
                Node(10, Offset(0.193f, 0.500f)),
                Node(11, Offset(0.313f, 0.292f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 0),
                Edge(6, 7), Edge(7, 8), Edge(8, 9), Edge(9, 10), Edge(10, 11), Edge(11, 6),
                Edge(0, 6), Edge(0, 11), Edge(1, 7), Edge(1, 6), Edge(2, 8), Edge(2, 7),
                Edge(3, 9), Edge(3, 8), Edge(4, 10), Edge(4, 9), Edge(5, 11), Edge(5, 10),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Six-fold symmetry, all even. Sweep in wedges, not in circles."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 32: The Lantern - 15 dots, 26 lines, path 2->13
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-13-12-11-10-9-14-12-10-14-13
        Level(
            id = 32,
            name = "The Lantern",
            nodes = listOf(
                Node(0, Offset(0.125f, 0.000f)),
                Node(1, Offset(0.333f, 0.000f)),
                Node(2, Offset(0.541f, 0.000f)),
                Node(3, Offset(0.125f, 0.208f)),
                Node(4, Offset(0.333f, 0.208f)),
                Node(5, Offset(0.541f, 0.208f)),
                Node(6, Offset(0.125f, 0.416f)),
                Node(7, Offset(0.333f, 0.416f)),
                Node(8, Offset(0.541f, 0.416f)),
                Node(9, Offset(0.458f, 0.802f)),
                Node(10, Offset(0.343f, 1.000f)),
                Node(11, Offset(0.114f, 1.000f)),
                Node(12, Offset(0.000f, 0.802f)),
                Node(13, Offset(0.114f, 0.604f)),
                Node(14, Offset(0.343f, 0.604f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(7, 8), Edge(9, 10), Edge(10, 11),
                Edge(11, 12), Edge(12, 13), Edge(13, 14), Edge(14, 9), Edge(10, 12), Edge(12, 14),
                Edge(14, 10), Edge(6, 13),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 13),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "A grid above a hexagon, tied by one line. The line is a one-way door."),
                    HintStep(text = "Start at the top-right dot; you will finish at the left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 33: The Anchor - 14 dots, 27 lines, path 2->9
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-9-10-11-12-13-9-11-13-10-12-9
        Level(
            id = 33,
            name = "The Anchor",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.226f, 0.000f)),
                Node(2, Offset(0.452f, 0.000f)),
                Node(3, Offset(0.000f, 0.226f)),
                Node(4, Offset(0.226f, 0.226f)),
                Node(5, Offset(0.452f, 0.226f)),
                Node(6, Offset(0.000f, 0.452f)),
                Node(7, Offset(0.226f, 0.452f)),
                Node(8, Offset(0.452f, 0.452f)),
                Node(9, Offset(0.226f, 0.632f)),
                Node(10, Offset(0.419f, 0.773f)),
                Node(11, Offset(0.345f, 1.000f)),
                Node(12, Offset(0.106f, 1.000f)),
                Node(13, Offset(0.033f, 0.773f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(7, 8), Edge(9, 10), Edge(10, 11),
                Edge(11, 12), Edge(12, 13), Edge(13, 9), Edge(9, 11), Edge(10, 12), Edge(11, 13),
                Edge(12, 9), Edge(13, 10), Edge(6, 9),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 9),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "A grid hangs from a star by one line. Cross it once and never come back."),
                    HintStep(text = "Start at the top-right dot; you will finish at the center one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 34: The Balloon - 14 dots, 27 lines, path 2->11
        // One solution: 2-0-1-2-3-4-0-3-1-4-2-7-6-5-8-6-9-7-10-9-8-11-9-12-10-13-12-11
        Level(
            id = 34,
            name = "The Balloon",
            nodes = listOf(
                Node(0, Offset(0.220f, 0.000f)),
                Node(1, Offset(0.397f, 0.129f)),
                Node(2, Offset(0.330f, 0.338f)),
                Node(3, Offset(0.110f, 0.338f)),
                Node(4, Offset(0.042f, 0.129f)),
                Node(5, Offset(0.000f, 0.560f)),
                Node(6, Offset(0.220f, 0.560f)),
                Node(7, Offset(0.440f, 0.560f)),
                Node(8, Offset(0.000f, 0.780f)),
                Node(9, Offset(0.220f, 0.780f)),
                Node(10, Offset(0.440f, 0.780f)),
                Node(11, Offset(0.000f, 1.000f)),
                Node(12, Offset(0.220f, 1.000f)),
                Node(13, Offset(0.440f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(5, 6), Edge(5, 8),
                Edge(8, 6), Edge(6, 7), Edge(6, 9), Edge(9, 7), Edge(7, 10), Edge(8, 9),
                Edge(8, 11), Edge(11, 9), Edge(9, 10), Edge(9, 12), Edge(12, 10), Edge(10, 13),
                Edge(11, 12), Edge(12, 13), Edge(2, 7),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 11),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "A star tied to a basket by one string. Cross the string exactly once."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 35: The Sunflower - 14 dots, 28 lines, circuit
        // One solution: 0-1-2-3-4-5-6-0-7-8-9-10-11-12-13-7-1-8-2-9-3-10-4-11-5-12-6-13-0
        Level(
            id = 35,
            name = "The Sunflower",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.901f, 0.193f)),
                Node(2, Offset(1.000f, 0.627f)),
                Node(3, Offset(0.723f, 0.975f)),
                Node(4, Offset(0.277f, 0.975f)),
                Node(5, Offset(0.000f, 0.627f)),
                Node(6, Offset(0.099f, 0.193f)),
                Node(7, Offset(0.622f, 0.259f)),
                Node(8, Offset(0.775f, 0.450f)),
                Node(9, Offset(0.721f, 0.689f)),
                Node(10, Offset(0.500f, 0.795f)),
                Node(11, Offset(0.279f, 0.689f)),
                Node(12, Offset(0.225f, 0.450f)),
                Node(13, Offset(0.378f, 0.259f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 6),
                Edge(6, 0), Edge(7, 8), Edge(8, 9), Edge(9, 10), Edge(10, 11), Edge(11, 12),
                Edge(12, 13), Edge(13, 7), Edge(0, 7), Edge(0, 13), Edge(1, 8), Edge(1, 7),
                Edge(2, 9), Edge(2, 8), Edge(3, 10), Edge(3, 9), Edge(4, 11), Edge(4, 10),
                Edge(5, 12), Edge(5, 11), Edge(6, 13), Edge(6, 12),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Seven petals, all even. Alternate inner and outer so nothing is stranded."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 36: The Constellation - 12 dots, 29 lines, path 2->3
        // One solution: 2-0-1-2-3-4-0-3-1-4-2-7-5-6-3-5-8-9-10-11-5-9-11-8-10-5-2-6-7-3
        Level(
            id = 36,
            name = "The Constellation",
            nodes = listOf(
                Node(0, Offset(0.175f, 0.000f)),
                Node(1, Offset(0.351f, 0.127f)),
                Node(2, Offset(0.284f, 0.333f)),
                Node(3, Offset(0.067f, 0.333f)),
                Node(4, Offset(0.000f, 0.127f)),
                Node(5, Offset(0.175f, 0.667f)),
                Node(6, Offset(0.000f, 0.539f)),
                Node(7, Offset(0.351f, 0.539f)),
                Node(8, Offset(0.351f, 0.794f)),
                Node(9, Offset(0.284f, 1.000f)),
                Node(10, Offset(0.067f, 1.000f)),
                Node(11, Offset(0.000f, 0.794f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(5, 6), Edge(6, 3),
                Edge(2, 7), Edge(7, 5), Edge(5, 3), Edge(6, 2), Edge(3, 7), Edge(2, 5),
                Edge(7, 6), Edge(5, 8), Edge(8, 9), Edge(9, 10), Edge(10, 11), Edge(11, 5),
                Edge(5, 9), Edge(8, 10), Edge(9, 11), Edge(10, 5), Edge(11, 8),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 3),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "Three stars in a column. The bottom star hangs from a single dot."),
                    HintStep(text = "Start at the top-right dot; you will finish at the top-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 37: The Fortress - 16 dots, 29 lines, path 5->10
        // One solution: 5-1-0-4-5-6-2-1-4-8-9-5-10-6-7-3-2-7-11-10-9-13-12-8-13-14-15-11-14-10
        Level(
            id = 37,
            name = "The Fortress",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.290f, 0.000f)),
                Node(2, Offset(0.580f, 0.000f)),
                Node(3, Offset(0.870f, 0.000f)),
                Node(4, Offset(0.000f, 0.333f)),
                Node(5, Offset(0.290f, 0.333f)),
                Node(6, Offset(0.580f, 0.333f)),
                Node(7, Offset(0.870f, 0.333f)),
                Node(8, Offset(0.000f, 0.667f)),
                Node(9, Offset(0.290f, 0.667f)),
                Node(10, Offset(0.580f, 0.667f)),
                Node(11, Offset(0.870f, 0.667f)),
                Node(12, Offset(0.000f, 1.000f)),
                Node(13, Offset(0.290f, 1.000f)),
                Node(14, Offset(0.580f, 1.000f)),
                Node(15, Offset(0.870f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 4), Edge(1, 2), Edge(1, 5), Edge(2, 3), Edge(2, 6),
                Edge(3, 7), Edge(4, 5), Edge(4, 8), Edge(5, 6), Edge(5, 9), Edge(6, 7),
                Edge(6, 10), Edge(7, 11), Edge(8, 9), Edge(8, 12), Edge(9, 10), Edge(9, 13),
                Edge(10, 11), Edge(10, 14), Edge(11, 15), Edge(12, 13), Edge(13, 14), Edge(14, 15),
                Edge(4, 1), Edge(2, 7), Edge(8, 13), Edge(14, 11), Edge(5, 10),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(5, 10),
                firstEdge = Pair(5, 1),
                steps = listOf(
                    HintStep(text = "Walls, corner braces and one bar across the courtyard. The odd dots are inside."),
                    HintStep(text = "Start at the top-left dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the top-left dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 38: The Tower - 15 dots, 30 lines, path 2->12
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-9-7-10-8-11-10-9-12-10-13-11-14-13-12
        Level(
            id = 38,
            name = "The Tower",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.227f, 0.000f)),
                Node(2, Offset(0.455f, 0.000f)),
                Node(3, Offset(0.000f, 0.250f)),
                Node(4, Offset(0.227f, 0.250f)),
                Node(5, Offset(0.455f, 0.250f)),
                Node(6, Offset(0.000f, 0.500f)),
                Node(7, Offset(0.227f, 0.500f)),
                Node(8, Offset(0.455f, 0.500f)),
                Node(9, Offset(0.000f, 0.750f)),
                Node(10, Offset(0.227f, 0.750f)),
                Node(11, Offset(0.455f, 0.750f)),
                Node(12, Offset(0.000f, 1.000f)),
                Node(13, Offset(0.227f, 1.000f)),
                Node(14, Offset(0.455f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(6, 9), Edge(9, 7), Edge(7, 8),
                Edge(7, 10), Edge(10, 8), Edge(8, 11), Edge(9, 10), Edge(9, 12), Edge(12, 10),
                Edge(10, 11), Edge(10, 13), Edge(13, 11), Edge(11, 14), Edge(12, 13), Edge(13, 14),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 12),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "Five storeys of braces. Odd dots at top-right and bottom-left."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 39: The Great Pyramid - 15 dots, 30 lines, circuit
        // One solution: 0-1-2-4-1-3-4-5-8-4-7-3-6-7-8-9-13-8-12-7-11-6-10-11-12-13-14-9-5-2-0
        Level(
            id = 39,
            name = "The Great Pyramid",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.375f, 0.217f)),
                Node(2, Offset(0.625f, 0.217f)),
                Node(3, Offset(0.250f, 0.435f)),
                Node(4, Offset(0.500f, 0.435f)),
                Node(5, Offset(0.750f, 0.435f)),
                Node(6, Offset(0.125f, 0.652f)),
                Node(7, Offset(0.375f, 0.652f)),
                Node(8, Offset(0.625f, 0.652f)),
                Node(9, Offset(0.875f, 0.652f)),
                Node(10, Offset(0.000f, 0.870f)),
                Node(11, Offset(0.250f, 0.870f)),
                Node(12, Offset(0.500f, 0.870f)),
                Node(13, Offset(0.750f, 0.870f)),
                Node(14, Offset(1.000f, 0.870f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(3, 7), Edge(4, 5), Edge(4, 7),
                Edge(4, 8), Edge(5, 8), Edge(5, 9), Edge(6, 7), Edge(6, 10), Edge(6, 11),
                Edge(7, 8), Edge(7, 11), Edge(7, 12), Edge(8, 9), Edge(8, 12), Edge(8, 13),
                Edge(9, 13), Edge(9, 14), Edge(10, 11), Edge(11, 12), Edge(12, 13), Edge(13, 14),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Fifteen dots, all even. Work row by row and keep a way back."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 40: The Mandala - 16 dots, 32 lines, circuit
        // One solution: 0-1-2-3-4-5-6-7-0-8-9-10-11-12-13-14-15-8-1-9-2-10-3-11-4-12-5-13-6-14-7-15-0
        Level(
            id = 40,
            name = "The Mandala",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.854f, 0.146f)),
                Node(2, Offset(1.000f, 0.500f)),
                Node(3, Offset(0.854f, 0.854f)),
                Node(4, Offset(0.500f, 1.000f)),
                Node(5, Offset(0.146f, 0.854f)),
                Node(6, Offset(0.000f, 0.500f)),
                Node(7, Offset(0.146f, 0.146f)),
                Node(8, Offset(0.619f, 0.214f)),
                Node(9, Offset(0.786f, 0.381f)),
                Node(10, Offset(0.786f, 0.619f)),
                Node(11, Offset(0.619f, 0.786f)),
                Node(12, Offset(0.381f, 0.786f)),
                Node(13, Offset(0.214f, 0.619f)),
                Node(14, Offset(0.214f, 0.381f)),
                Node(15, Offset(0.381f, 0.214f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 5), Edge(5, 6),
                Edge(6, 7), Edge(7, 0), Edge(8, 9), Edge(9, 10), Edge(10, 11), Edge(11, 12),
                Edge(12, 13), Edge(13, 14), Edge(14, 15), Edge(15, 8), Edge(0, 8), Edge(0, 15),
                Edge(1, 9), Edge(1, 8), Edge(2, 10), Edge(2, 9), Edge(3, 11), Edge(3, 10),
                Edge(4, 12), Edge(4, 11), Edge(5, 13), Edge(5, 12), Edge(6, 14), Edge(6, 13),
                Edge(7, 15), Edge(7, 14),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                firstEdge = Pair(0, 1),
                steps = listOf(
                    HintStep(text = "Sixteen dots, thirty-two lines, all even. Wedges, not circles."),
                    HintStep(text = "Every dot works as a start. Try the top one.", showValidStarts = true),
                    HintStep(text = "From the top dot, head down-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 41: The Bow Tie Grid - 17 dots, 32 lines, path 2->14
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-10-9-11-10-12-6-13-12-11-14-12-15-13-16-15-14
        Level(
            id = 41,
            name = "The Bow Tie Grid",
            nodes = listOf(
                Node(0, Offset(0.500f, 0.000f)),
                Node(1, Offset(0.750f, 0.000f)),
                Node(2, Offset(1.000f, 0.000f)),
                Node(3, Offset(0.500f, 0.250f)),
                Node(4, Offset(0.750f, 0.250f)),
                Node(5, Offset(1.000f, 0.250f)),
                Node(6, Offset(0.500f, 0.500f)),
                Node(7, Offset(0.750f, 0.500f)),
                Node(8, Offset(1.000f, 0.500f)),
                Node(9, Offset(0.000f, 0.500f)),
                Node(10, Offset(0.250f, 0.500f)),
                Node(11, Offset(0.000f, 0.750f)),
                Node(12, Offset(0.250f, 0.750f)),
                Node(13, Offset(0.500f, 0.750f)),
                Node(14, Offset(0.000f, 1.000f)),
                Node(15, Offset(0.250f, 1.000f)),
                Node(16, Offset(0.500f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(7, 8), Edge(9, 10), Edge(9, 11),
                Edge(11, 10), Edge(10, 6), Edge(10, 12), Edge(12, 6), Edge(6, 13), Edge(11, 12),
                Edge(11, 14), Edge(14, 12), Edge(12, 13), Edge(12, 15), Edge(15, 13), Edge(13, 16),
                Edge(14, 15), Edge(15, 16),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 14),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "Two grids pinched at a single dot. That dot is the only door between them."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 42: The Diamond - 16 dots, 33 lines, path 6->9
        // One solution: 6-3-1-0-2-1-4-2-5-4-3-7-4-8-5-9-8-7-6-13-11-10-12-11-14-12-15-14-13-7-14-8-15-9
        Level(
            id = 42,
            name = "The Diamond",
            nodes = listOf(
                Node(0, Offset(0.287f, 0.000f)),
                Node(1, Offset(0.192f, 0.167f)),
                Node(2, Offset(0.383f, 0.167f)),
                Node(3, Offset(0.096f, 0.333f)),
                Node(4, Offset(0.287f, 0.333f)),
                Node(5, Offset(0.479f, 0.333f)),
                Node(6, Offset(0.000f, 0.500f)),
                Node(7, Offset(0.192f, 0.500f)),
                Node(8, Offset(0.383f, 0.500f)),
                Node(9, Offset(0.575f, 0.500f)),
                Node(10, Offset(0.287f, 1.000f)),
                Node(11, Offset(0.192f, 0.833f)),
                Node(12, Offset(0.383f, 0.833f)),
                Node(13, Offset(0.096f, 0.667f)),
                Node(14, Offset(0.287f, 0.667f)),
                Node(15, Offset(0.479f, 0.667f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(3, 7), Edge(4, 5), Edge(4, 7),
                Edge(4, 8), Edge(5, 8), Edge(5, 9), Edge(6, 7), Edge(7, 8), Edge(8, 9),
                Edge(10, 11), Edge(10, 12), Edge(11, 12), Edge(11, 13), Edge(11, 14), Edge(12, 14),
                Edge(12, 15), Edge(13, 14), Edge(13, 6), Edge(13, 7), Edge(14, 15), Edge(14, 7),
                Edge(14, 8), Edge(15, 8), Edge(15, 9),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(6, 9),
                firstEdge = Pair(6, 3),
                steps = listOf(
                    HintStep(text = "Two pyramids on a shared base. The tips are the odd dots."),
                    HintStep(text = "Start at the left dot; you will finish at the right one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 43: The Net - 16 dots, 33 lines, path 3->12
        // One solution: 3-2-1-0-4-1-5-2-6-3-7-6-5-4-8-5-9-6-10-7-11-10-9-8-12-9-13-10-14-11-15-14-13-12
        Level(
            id = 43,
            name = "The Net",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.290f, 0.000f)),
                Node(2, Offset(0.580f, 0.000f)),
                Node(3, Offset(0.870f, 0.000f)),
                Node(4, Offset(0.000f, 0.333f)),
                Node(5, Offset(0.290f, 0.333f)),
                Node(6, Offset(0.580f, 0.333f)),
                Node(7, Offset(0.870f, 0.333f)),
                Node(8, Offset(0.000f, 0.667f)),
                Node(9, Offset(0.290f, 0.667f)),
                Node(10, Offset(0.580f, 0.667f)),
                Node(11, Offset(0.870f, 0.667f)),
                Node(12, Offset(0.000f, 1.000f)),
                Node(13, Offset(0.290f, 1.000f)),
                Node(14, Offset(0.580f, 1.000f)),
                Node(15, Offset(0.870f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 4), Edge(4, 1), Edge(1, 2), Edge(1, 5), Edge(5, 2),
                Edge(2, 3), Edge(2, 6), Edge(6, 3), Edge(3, 7), Edge(4, 5), Edge(4, 8),
                Edge(8, 5), Edge(5, 6), Edge(5, 9), Edge(9, 6), Edge(6, 7), Edge(6, 10),
                Edge(10, 7), Edge(7, 11), Edge(8, 9), Edge(8, 12), Edge(12, 9), Edge(9, 10),
                Edge(9, 13), Edge(13, 10), Edge(10, 11), Edge(10, 14), Edge(14, 11), Edge(11, 15),
                Edge(12, 13), Edge(13, 14), Edge(14, 15),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(3, 12),
                firstEdge = Pair(3, 2),
                steps = listOf(
                    HintStep(text = "Thirty-three lines. Odd dots at two corners; the inside can strand you."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 44: The Twin Towers - 18 dots, 33 lines, path 2->15
        // One solution: 2-1-0-3-1-4-2-5-4-3-6-4-7-5-8-7-6-11-10-9-12-10-13-11-14-13-12-15-13-16-14-17-16-15
        Level(
            id = 44,
            name = "The Twin Towers",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.200f, 0.000f)),
                Node(2, Offset(0.400f, 0.000f)),
                Node(3, Offset(0.000f, 0.200f)),
                Node(4, Offset(0.200f, 0.200f)),
                Node(5, Offset(0.400f, 0.200f)),
                Node(6, Offset(0.000f, 0.400f)),
                Node(7, Offset(0.200f, 0.400f)),
                Node(8, Offset(0.400f, 0.400f)),
                Node(9, Offset(0.400f, 0.600f)),
                Node(10, Offset(0.200f, 0.600f)),
                Node(11, Offset(0.000f, 0.600f)),
                Node(12, Offset(0.400f, 0.800f)),
                Node(13, Offset(0.200f, 0.800f)),
                Node(14, Offset(0.000f, 0.800f)),
                Node(15, Offset(0.400f, 1.000f)),
                Node(16, Offset(0.200f, 1.000f)),
                Node(17, Offset(0.000f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 3), Edge(3, 1), Edge(1, 2), Edge(1, 4), Edge(4, 2),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(6, 4), Edge(4, 5), Edge(4, 7),
                Edge(7, 5), Edge(5, 8), Edge(6, 7), Edge(7, 8), Edge(9, 10), Edge(9, 12),
                Edge(12, 10), Edge(10, 11), Edge(10, 13), Edge(13, 11), Edge(11, 14), Edge(12, 13),
                Edge(12, 15), Edge(15, 13), Edge(13, 14), Edge(13, 16), Edge(16, 14), Edge(14, 17),
                Edge(15, 16), Edge(16, 17), Edge(6, 11),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 15),
                firstEdge = Pair(2, 1),
                steps = listOf(
                    HintStep(text = "Two braced grids and one tie. Nothing may be stranded when you switch."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 45: The Chandelier - 17 dots, 34 lines, path 2->13
        // One solution: 2-0-1-2-3-4-0-3-1-4-2-8-7-6-5-9-6-10-7-11-8-12-11-10-9-13-10-14-11-15-12-16-15-14-13
        Level(
            id = 45,
            name = "The Chandelier",
            nodes = listOf(
                Node(0, Offset(0.501f, 0.000f)),
                Node(1, Offset(0.675f, 0.126f)),
                Node(2, Offset(0.609f, 0.330f)),
                Node(3, Offset(0.394f, 0.330f)),
                Node(4, Offset(0.328f, 0.126f)),
                Node(5, Offset(0.000f, 0.513f)),
                Node(6, Offset(0.203f, 0.513f)),
                Node(7, Offset(0.406f, 0.513f)),
                Node(8, Offset(0.609f, 0.513f)),
                Node(9, Offset(0.000f, 0.756f)),
                Node(10, Offset(0.203f, 0.756f)),
                Node(11, Offset(0.406f, 0.756f)),
                Node(12, Offset(0.609f, 0.756f)),
                Node(13, Offset(0.000f, 1.000f)),
                Node(14, Offset(0.203f, 1.000f)),
                Node(15, Offset(0.406f, 1.000f)),
                Node(16, Offset(0.609f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(1, 2), Edge(2, 3), Edge(3, 4), Edge(4, 0), Edge(0, 2),
                Edge(1, 3), Edge(2, 4), Edge(3, 0), Edge(4, 1), Edge(5, 6), Edge(5, 9),
                Edge(9, 6), Edge(6, 7), Edge(6, 10), Edge(10, 7), Edge(7, 8), Edge(7, 11),
                Edge(11, 8), Edge(8, 12), Edge(9, 10), Edge(9, 13), Edge(13, 10), Edge(10, 11),
                Edge(10, 14), Edge(14, 11), Edge(11, 12), Edge(11, 15), Edge(15, 12), Edge(12, 16),
                Edge(13, 14), Edge(14, 15), Edge(15, 16), Edge(2, 8),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(2, 13),
                firstEdge = Pair(2, 0),
                steps = listOf(
                    HintStep(text = "A star hangs over a wide deck by one chain. Which side do you start on?"),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 46: The Obelisk - 18 dots, 38 lines, path 6->14
        // One solution: 6-3-1-0-2-1-4-2-5-4-3-7-4-8-5-9-8-7-6-10-7-11-8-12-9-13-12-11-10-14-11-15-12-16-13-17-16-15-14
        Level(
            id = 46,
            name = "The Obelisk",
            nodes = listOf(
                Node(0, Offset(0.299f, 0.000f)),
                Node(1, Offset(0.200f, 0.174f)),
                Node(2, Offset(0.399f, 0.174f)),
                Node(3, Offset(0.100f, 0.347f)),
                Node(4, Offset(0.299f, 0.347f)),
                Node(5, Offset(0.499f, 0.347f)),
                Node(6, Offset(0.000f, 0.521f)),
                Node(7, Offset(0.200f, 0.521f)),
                Node(8, Offset(0.399f, 0.521f)),
                Node(9, Offset(0.599f, 0.521f)),
                Node(10, Offset(0.000f, 0.760f)),
                Node(11, Offset(0.200f, 0.760f)),
                Node(12, Offset(0.399f, 0.760f)),
                Node(13, Offset(0.599f, 0.760f)),
                Node(14, Offset(0.000f, 1.000f)),
                Node(15, Offset(0.200f, 1.000f)),
                Node(16, Offset(0.399f, 1.000f)),
                Node(17, Offset(0.599f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(3, 7), Edge(4, 5), Edge(4, 7),
                Edge(4, 8), Edge(5, 8), Edge(5, 9), Edge(6, 7), Edge(7, 8), Edge(8, 9),
                Edge(6, 10), Edge(10, 7), Edge(7, 11), Edge(11, 8), Edge(8, 12), Edge(12, 9),
                Edge(9, 13), Edge(10, 11), Edge(10, 14), Edge(14, 11), Edge(11, 12), Edge(11, 15),
                Edge(15, 12), Edge(12, 13), Edge(12, 16), Edge(16, 13), Edge(13, 17), Edge(14, 15),
                Edge(15, 16), Edge(16, 17),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(6, 14),
                firstEdge = Pair(6, 3),
                steps = listOf(
                    HintStep(text = "A pyramid on a braced base. One odd dot hides where the two meet."),
                    HintStep(text = "Start at the left dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 47: The Keep - 20 dots, 39 lines, path 8->11
        // One solution: 8-4-0-1-2-3-7-6-2-7-11-10-6-5-1-4-5-9-8-12-13-9-10-14-13-17-16-12-17-18-14-15-19-18-15-11-6-9-14-11
        Level(
            id = 47,
            name = "The Keep",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.227f, 0.000f)),
                Node(2, Offset(0.455f, 0.000f)),
                Node(3, Offset(0.682f, 0.000f)),
                Node(4, Offset(0.000f, 0.250f)),
                Node(5, Offset(0.227f, 0.250f)),
                Node(6, Offset(0.455f, 0.250f)),
                Node(7, Offset(0.682f, 0.250f)),
                Node(8, Offset(0.000f, 0.500f)),
                Node(9, Offset(0.227f, 0.500f)),
                Node(10, Offset(0.455f, 0.500f)),
                Node(11, Offset(0.682f, 0.500f)),
                Node(12, Offset(0.000f, 0.750f)),
                Node(13, Offset(0.227f, 0.750f)),
                Node(14, Offset(0.455f, 0.750f)),
                Node(15, Offset(0.682f, 0.750f)),
                Node(16, Offset(0.000f, 1.000f)),
                Node(17, Offset(0.227f, 1.000f)),
                Node(18, Offset(0.455f, 1.000f)),
                Node(19, Offset(0.682f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 4), Edge(1, 2), Edge(1, 5), Edge(2, 3), Edge(2, 6),
                Edge(3, 7), Edge(4, 5), Edge(4, 8), Edge(5, 6), Edge(5, 9), Edge(6, 7),
                Edge(6, 10), Edge(7, 11), Edge(8, 9), Edge(8, 12), Edge(9, 10), Edge(9, 13),
                Edge(10, 11), Edge(10, 14), Edge(11, 15), Edge(12, 13), Edge(12, 16), Edge(13, 14),
                Edge(13, 17), Edge(14, 15), Edge(14, 18), Edge(15, 19), Edge(16, 17), Edge(17, 18),
                Edge(18, 19), Edge(4, 1), Edge(2, 7), Edge(12, 17), Edge(18, 15), Edge(9, 6),
                Edge(6, 11), Edge(14, 11), Edge(9, 14),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(8, 11),
                firstEdge = Pair(8, 4),
                steps = listOf(
                    HintStep(text = "Corner braces, a diamond in the courtyard. The odd dots are halfway up the walls."),
                    HintStep(text = "Start at the left dot; you will finish at the right one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 48: The Spire - 20 dots, 41 lines, path 6->13
        // One solution: 6-2-1-0-4-1-5-2-3-7-6-5-4-8-5-9-6-10-7-11-10-9-8-12-9-13-10-14-11-15-14-13-12-16-17-14-18-15-19-18-17-13
        Level(
            id = 48,
            name = "The Spire",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.227f, 0.000f)),
                Node(2, Offset(0.455f, 0.000f)),
                Node(3, Offset(0.682f, 0.000f)),
                Node(4, Offset(0.000f, 0.250f)),
                Node(5, Offset(0.227f, 0.250f)),
                Node(6, Offset(0.455f, 0.250f)),
                Node(7, Offset(0.682f, 0.250f)),
                Node(8, Offset(0.000f, 0.500f)),
                Node(9, Offset(0.227f, 0.500f)),
                Node(10, Offset(0.455f, 0.500f)),
                Node(11, Offset(0.682f, 0.500f)),
                Node(12, Offset(0.000f, 0.750f)),
                Node(13, Offset(0.227f, 0.750f)),
                Node(14, Offset(0.455f, 0.750f)),
                Node(15, Offset(0.682f, 0.750f)),
                Node(16, Offset(0.000f, 1.000f)),
                Node(17, Offset(0.227f, 1.000f)),
                Node(18, Offset(0.455f, 1.000f)),
                Node(19, Offset(0.682f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 4), Edge(4, 1), Edge(1, 2), Edge(1, 5), Edge(5, 2),
                Edge(2, 3), Edge(2, 6), Edge(3, 7), Edge(4, 5), Edge(4, 8), Edge(8, 5),
                Edge(5, 6), Edge(5, 9), Edge(9, 6), Edge(6, 7), Edge(6, 10), Edge(10, 7),
                Edge(7, 11), Edge(8, 9), Edge(8, 12), Edge(12, 9), Edge(9, 10), Edge(9, 13),
                Edge(13, 10), Edge(10, 11), Edge(10, 14), Edge(14, 11), Edge(11, 15), Edge(12, 13),
                Edge(12, 16), Edge(13, 14), Edge(13, 17), Edge(17, 14), Edge(14, 15), Edge(14, 18),
                Edge(18, 15), Edge(15, 19), Edge(16, 17), Edge(17, 18), Edge(18, 19),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(6, 13),
                firstEdge = Pair(6, 2),
                steps = listOf(
                    HintStep(text = "Twenty dots. The odd dots have moved one step inside; find them first."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head up first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 49: The Monument - 22 dots, 42 lines, path 6->18
        // One solution: 6-3-1-0-2-1-4-2-5-4-3-7-4-8-5-9-8-7-6-13-12-11-10-14-11-15-12-16-13-17-16-15-14-18-15-19-16-20-17-21-20-19-18
        Level(
            id = 49,
            name = "The Monument",
            nodes = listOf(
                Node(0, Offset(0.268f, 0.000f)),
                Node(1, Offset(0.179f, 0.155f)),
                Node(2, Offset(0.357f, 0.155f)),
                Node(3, Offset(0.089f, 0.311f)),
                Node(4, Offset(0.268f, 0.311f)),
                Node(5, Offset(0.446f, 0.311f)),
                Node(6, Offset(0.000f, 0.466f)),
                Node(7, Offset(0.179f, 0.466f)),
                Node(8, Offset(0.357f, 0.466f)),
                Node(9, Offset(0.536f, 0.466f)),
                Node(10, Offset(0.536f, 0.643f)),
                Node(11, Offset(0.357f, 0.643f)),
                Node(12, Offset(0.179f, 0.643f)),
                Node(13, Offset(0.000f, 0.643f)),
                Node(14, Offset(0.536f, 0.821f)),
                Node(15, Offset(0.357f, 0.821f)),
                Node(16, Offset(0.179f, 0.821f)),
                Node(17, Offset(0.000f, 0.821f)),
                Node(18, Offset(0.536f, 1.000f)),
                Node(19, Offset(0.357f, 1.000f)),
                Node(20, Offset(0.179f, 1.000f)),
                Node(21, Offset(0.000f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 2), Edge(1, 2), Edge(1, 3), Edge(1, 4), Edge(2, 4),
                Edge(2, 5), Edge(3, 4), Edge(3, 6), Edge(3, 7), Edge(4, 5), Edge(4, 7),
                Edge(4, 8), Edge(5, 8), Edge(5, 9), Edge(6, 7), Edge(7, 8), Edge(8, 9),
                Edge(10, 11), Edge(10, 14), Edge(14, 11), Edge(11, 12), Edge(11, 15), Edge(15, 12),
                Edge(12, 13), Edge(12, 16), Edge(16, 13), Edge(13, 17), Edge(14, 15), Edge(14, 18),
                Edge(18, 15), Edge(15, 16), Edge(15, 19), Edge(19, 16), Edge(16, 17), Edge(16, 20),
                Edge(20, 17), Edge(17, 21), Edge(18, 19), Edge(19, 20), Edge(20, 21), Edge(6, 13),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(6, 18),
                firstEdge = Pair(6, 3),
                steps = listOf(
                    HintStep(text = "A pyramid on a plinth, joined by one line. Finish the top before you descend."),
                    HintStep(text = "Start at the left dot; you will finish at the bottom-right one.", showValidStarts = true),
                    HintStep(text = "From the left dot, head up-right first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),

        // Level 50: The Citadel - 20 dots, 43 lines, path 3->16
        // One solution: 3-2-1-0-4-1-5-2-6-3-7-6-5-4-8-5-9-6-10-7-11-10-9-8-12-9-13-10-14-11-15-14-13-12-16-13-17-14-18-15-19-18-17-16
        Level(
            id = 50,
            name = "The Citadel",
            nodes = listOf(
                Node(0, Offset(0.000f, 0.000f)),
                Node(1, Offset(0.227f, 0.000f)),
                Node(2, Offset(0.455f, 0.000f)),
                Node(3, Offset(0.682f, 0.000f)),
                Node(4, Offset(0.000f, 0.250f)),
                Node(5, Offset(0.227f, 0.250f)),
                Node(6, Offset(0.455f, 0.250f)),
                Node(7, Offset(0.682f, 0.250f)),
                Node(8, Offset(0.000f, 0.500f)),
                Node(9, Offset(0.227f, 0.500f)),
                Node(10, Offset(0.455f, 0.500f)),
                Node(11, Offset(0.682f, 0.500f)),
                Node(12, Offset(0.000f, 0.750f)),
                Node(13, Offset(0.227f, 0.750f)),
                Node(14, Offset(0.455f, 0.750f)),
                Node(15, Offset(0.682f, 0.750f)),
                Node(16, Offset(0.000f, 1.000f)),
                Node(17, Offset(0.227f, 1.000f)),
                Node(18, Offset(0.455f, 1.000f)),
                Node(19, Offset(0.682f, 1.000f)),
            ),
            edges = listOf(
                Edge(0, 1), Edge(0, 4), Edge(4, 1), Edge(1, 2), Edge(1, 5), Edge(5, 2),
                Edge(2, 3), Edge(2, 6), Edge(6, 3), Edge(3, 7), Edge(4, 5), Edge(4, 8),
                Edge(8, 5), Edge(5, 6), Edge(5, 9), Edge(9, 6), Edge(6, 7), Edge(6, 10),
                Edge(10, 7), Edge(7, 11), Edge(8, 9), Edge(8, 12), Edge(12, 9), Edge(9, 10),
                Edge(9, 13), Edge(13, 10), Edge(10, 11), Edge(10, 14), Edge(14, 11), Edge(11, 15),
                Edge(12, 13), Edge(12, 16), Edge(16, 13), Edge(13, 14), Edge(13, 17), Edge(17, 14),
                Edge(14, 15), Edge(14, 18), Edge(18, 15), Edge(15, 19), Edge(16, 17), Edge(17, 18),
                Edge(18, 19),
            ),
            hints = LevelHints(
                validStartNodeIds = listOf(3, 16),
                firstEdge = Pair(3, 2),
                steps = listOf(
                    HintStep(text = "Forty-three lines. Odd dots at top-right and bottom-left. Keep the middle for last."),
                    HintStep(text = "Start at the top-right dot; you will finish at the bottom-left one.", showValidStarts = true),
                    HintStep(text = "From the top-right dot, head left first.", showValidStarts = true, showFirstEdge = true),
                ),
            ),
        ),
    )

    fun getLevel(id: Int): Level? = levels.firstOrNull { it.id == id }

    fun getNextLevel(currentLevelId: Int): Level? {
        val currentIndex = levels.indexOfFirst { it.id == currentLevelId }
        return levels.getOrNull(currentIndex + 1)
    }
}
