"""Generates Graph.kt (levels + hints) from the catalog."""
from __future__ import annotations

import math

from geometry import LevelSpec, solve

HEADER = '''package app.curious.lineflow

import androidx.compose.ui.geometry.Offset

data class Node(
    val id: Int,
    // Position in a normalized coordinate space (0.0 to 1.0)
    val position: Offset,
)

data class Edge(
    val node1Id: Int,
    val node2Id: Int,
    var isVisited: Boolean = false,
) {
    fun containsNode(nodeId: Int): Boolean = nodeId == node1Id || nodeId == node2Id
}

data class HintStep(
    val text: String,
    val showValidStarts: Boolean = false,
    val showFirstEdge: Boolean = false,
)

data class LevelHints(
    val validStartNodeIds: List<Int>,
    val firstEdge: Pair<Int, Int>?,
    val steps: List<HintStep>,
)

data class Level(
    val id: Int,
    val name: String,
    val nodes: List<Node>,
    val edges: List<Edge>,
    val hints: LevelHints,
)

/**
 * All levels are generated by `.scripts/leveldesign/build.py --write`.
 * Edit the catalog there, not this file: every level is verified to be
 * drawable in one stroke and laid out with enough room for a finger.
 */
object LevelManager {
    val levels = listOf(
'''

FOOTER = '''    )

    fun getLevel(id: Int): Level? = levels.firstOrNull { it.id == id }

    fun getNextLevel(currentLevelId: Int): Level? {
        val currentIndex = levels.indexOfFirst { it.id == currentLevelId }
        return levels.getOrNull(currentIndex + 1)
    }
}
'''


def region(p, pts) -> str:
    """Rough on-screen position word for a point, e.g. 'top-left'."""
    xs = [q[0] for q in pts]
    ys = [q[1] for q in pts]
    w = max(xs) - min(xs) or 1.0
    h = max(ys) - min(ys) or 1.0
    fx = (p[0] - min(xs)) / w
    fy = (p[1] - min(ys)) / h
    col = "left" if fx < 0.34 else "right" if fx > 0.66 else ""
    row = "top" if fy < 0.34 else "bottom" if fy > 0.66 else ""
    if row and col:
        return f"{row}-{col}"
    if row:
        return row
    if col:
        return col
    return "center"


def direction(a, b) -> str:
    ang = math.degrees(math.atan2(-(b[1] - a[1]), b[0] - a[0])) % 360  # y up
    names = ["right", "up-right", "up", "up-left", "left", "down-left", "down", "down-right"]
    return names[int(((ang + 22.5) % 360) // 45)]


def hint_steps(spec: LevelSpec, start: int, first: int) -> list[tuple[str, bool, bool]]:
    pts = spec.nodes
    where = region(pts[start], pts)
    towards = direction(pts[start], pts[first])
    circuit = len(spec.odd_nodes()) == 0
    if circuit:
        locate = f"Every dot works as a start. Try the {where} one."
    else:
        odd = spec.odd_nodes()
        other = [n for n in odd if n != start][0]
        locate = f"Start at the {where} dot; you will finish at the {region(pts[other], pts)} one."
    move = f"From the {where} dot, head {towards} first."
    if spec.id <= 10:
        return [(spec.insight, False, False), (f"{locate} {move}", True, True)]
    return [(spec.insight, False, False), (locate, True, False), (move, True, True)]


def kotlin_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render_level(spec: LevelSpec) -> str:
    start, first, trail = solve(spec)
    pts = spec.normalized()
    deg = spec.degree()
    odd = spec.odd_nodes()
    kind = "circuit" if not odd else f"path {odd[0]}->{odd[1]}"
    out = []
    out.append(f"        // Level {spec.id}: {spec.name} - {len(pts)} dots, {len(spec.edges)} lines, {kind}")
    out.append(f"        // One solution: {'-'.join(str(n) for n in trail)}")
    out.append("        Level(")
    out.append(f"            id = {spec.id},")
    out.append(f"            name = {kotlin_str(spec.name)},")
    out.append("            nodes = listOf(")
    for i, (x, y) in enumerate(pts):
        out.append(f"                Node({i}, Offset({x:.3f}f, {y:.3f}f)),")
    out.append("            ),")
    out.append("            edges = listOf(")
    row = []
    for a, b in spec.edges:
        row.append(f"Edge({a}, {b})")
        if len(row) == 6:
            out.append("                " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("                " + ", ".join(row) + ",")
    out.append("            ),")
    out.append("            hints = LevelHints(")
    out.append(f"                validStartNodeIds = listOf({', '.join(str(n) for n in spec.valid_starts())}),")
    out.append(f"                firstEdge = Pair({start}, {first}),")
    out.append("                steps = listOf(")
    for text, starts, edge in hint_steps(spec, start, first):
        flags = ""
        if starts:
            flags += ", showValidStarts = true"
        if edge:
            flags += ", showFirstEdge = true"
        out.append(f"                    HintStep(text = {kotlin_str(text)}{flags}),")
    out.append("                ),")
    out.append("            ),")
    out.append("        ),")
    return "\n".join(out)


def render_graph_kt(levels: list[LevelSpec]) -> str:
    body = "\n\n".join(render_level(lv) for lv in levels)
    return HEADER + body + "\n" + FOOTER
